 - name: Update and upgrade apt packages
   apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
   tags: [ ubuntu,openresty,lapis ]

 - name: Install luarocks
   apt:
    name: luarocks 
    state: present
   tags: [ openresty,lapis ]
 
 - name: Copy cdn dependencies  script
   template:
    src:  cdn-dependencies.sh.j2
    dest: /tmp/cdn-dependencies.sh
    mode: 0777
   tags: [ openresty,lapis ]

 - name: Copy openresty script
   template:
    src:  openresty.sh.j2 
    dest: /tmp/openresty.sh 
    mode: 0777
   tags: [ openresty,lapis ] 
 
 - name: Execute the script
   shell: /tmp/openresty.sh
   async: 1800
   poll: 1800
   tags: [ openresty,lapis ]
 
 - name: Deploy OpenResty systemd service file
   template:
      src: openresty.service.j2
      dest: /etc/systemd/system/openresty.service
   notify: Reload systemd
   tags: [ openresty,lapis ]

 - name: copy nginx conf file
   template:
      src: nginx.conf.j2
      dest: /usr/local/openresty/nginx/conf/nginx.conf 
   notify: Restart openresty
   tags: [ openresty,lapis ]

 - name: Enable and start OpenResty service
   systemd:
       name: openresty
       state: started
       enabled: yes 
   tags: [ openresty,lapis ]
