 - name: Update and upgrade apt packages
   apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
   tags: [ubuntu]

 - name: Install luarocks
   apt:
    name: luarocks 
    state: present
   tags: [ luarocks,openresty ]

 - name: Copy openresty script
   become: yes
   become_user: root
   copy:
    src:  /Users/sreejit/opsapi/openresty.sh 
    dest: /root/openresty.sh 
    mode: 0777
    remote_src: yes
   tags: [ luarocks,openresty]
 
 - name: Execute the script
   become: yes
   become_user: root   
   shell: /root/openresty.sh
   tags: [ luarocks,openresty]
 
 - name: Deploy OpenResty systemd service file
   template:
      src: openresty.service.j2
      dest: /etc/systemd/system/openresty.service
   notify: Reload systemd
   tags: [luarocks,openresty]

 - name: copy nginx conf file
   template:
      src: nginx.conf.j2
      dest: /usr/local/openresty/nginx/conf/nginx.conf 
   notify: Restart openresty
   tags: [luarocks,openresty]

 - name: Enable and start OpenResty service
   systemd:
       name: openresty
       state: started
       enabled: yes 
   tags: [ luarocks,openresty]
