name: Ansible compile from source and install Openresty

on:
  push:
    branches:
      - workflow-opsapi 
  pull_request:
    branches:
      - workflow-opsapi

  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target environment'
        default: 'int'
        required: true
        options:
            - int
            - test
            - acc
            - prod

env:
  TARGET_ENV: ${{ github.event.inputs.TARGET_ENV || 'int' }}
  API_DOMAINNAME_ENDPOINT:  ${{ github.event.inputs.TARGET_ENV || 'int' }}.opsapi.org
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Install Ansible on Ubuntu Latest
        run: |
          sudo apt-get install -y ansible
          export ANSIBLE_HOST_KEY_CHECKING=False

      - name: Decrypt Ansible Vault file
        env:
          VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          ansible-vault decrypt devops/ansible/id_rsa --vault-password-file=<(echo $VAULT_PASSWORD)

      - name: Add SSH Host Key for hosts
        run: |
         mkdir -p ~/.ssh
         ssh-keyscan -H `cat devops/ansible/hosts | grep ansible_user | awk '{print $1}'`  >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook devops/ansible/installopenresty.yml -i hosts 
        env:
          ANSIBLE_PRIVATE_KEY_FILE: id_rsa
