name: Ansible Openresty build

on:
  push:
    branches:
      - workflow-opsapi
  pull_request:
    branches:
      - workflow-opsapi
env: 
  ENV_TARGET_SSH_PRIVATE_KEY: ${{ secrets.TARGET_SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 1
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo ${{ env.ENV_TARGET_SSH_PRIVATE_KEY }} >> /tmp/file.txt
          cat /tmp/file.txt
          sudo apt-get install -y ansible 
