name: Ansible Openresty build

on:
  push:
    branches:
      - workflow-opsapi
  pull_request:
    branches:
      - workflow-opsapi
env: 
  ENV_TARGET_SSH_PRIVATE_KEY: ${{ secrets.SR_SREE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 1
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo env.ENV_TARGET_SSH_PRIVATE_KEY >>/tmp/file.txt
          cat /tmp/file.txt
          sudo chmod 600 /tmp/file.txt
          sudo apt-get install -y ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook installopenresty.yml -i hosts --private-key /tmp/file.txt
