name: Ansible Openresty build

on:
  push:
    branches:
      - workflow-opsapi
  pull_request:
    branches:
      - workflow-opsapi
env: 
  ENV_TARGET_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 1
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook installopenresty.yml  -i hosts
