name: Ansible compile from source and install Openresty

on:
  push:
    branches:
      - workflow-secure 
  pull_request:
    branches:
      - workflow-opsapi

  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target environment'
        default: 'int'
        required: true
        options:
            - int
            - test
            - acc
            - prod

env:
  TARGET_ENV: ${{ github.event.inputs.TARGET_ENV || 'int' }}
  API_DOMAINNAME_ENDPOINT:  ${{ github.event.inputs.TARGET_ENV || 'int' }}.opsapi.org
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Install Ansible on Ubuntu Latest
        run: |
          sudo apt-get install -y ansible
      - name: Decrypt Ansible Vault file
        run: |
          mkdir -p ~/.ansible
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.ansible/vault_pass.txt
      - name: Run Ansible Playbook
        run: |
          ansible-playbook installopenresty.yml --vault-password-file ~/.ansible/vault_pass.txt  -i hosts
        env:
          ANSIBLE_CONFIG: ansible.cfg
