name: Docker OPSAPI Image build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    IMAGE_REGISTRY: bwalia
    TARGET_STACK: openresty_lua
    IMAGE_NAME: opsapi
    TARGET_IMAGE_TAG: latest
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build OPSAPI Docker image based on the TARGET PLATFORM Image and push to Docker Hub
      run: |
        echo "OPSAPI Docker image builder!"
        echo "Build, tag, and push image to the given Docker Registry."
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
        docker build -f Dockerfile --build-arg TAG=latest -t test-${{ env.TARGET_STACK }} . --no-cache
        docker tag test-${{ env.TARGET_STACK }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
        docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
      shell: bash        

    - name: Run Docker container
      run: |
            docker run -d -p 80:80 bwalia/opsapi:latest openresty -g "daemon off;"

    - name: Verify OpenResty is running
      run: |
            sleep 10 # Give some time for the server to start
            curl -I http://localhost:80