name: cloudflare workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Install Ansible on Ubuntu Latest
        run: |
          sudo apt-get install -y ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
      - name: Run Ansible Playbook
        run: |
          ansible-playbook devops/ansible/playbook_openresty.yml -i devops/ansible/hosts tags="cloudflare" -l 94.72.96.175
        env:
          ANSIBLE_PRIVATE_KEY_FILE: id_rsa

